#!/usr/bin/env python3
"""Fill German msgstr entries from POT using embedded translations."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
POT = ROOT / "po" / "org.robertsm.wallhaven.pot"
DE_PO = ROOT / "po" / "de.po"

# Exact English → German strings (390 UI entries)
DE: dict[str, str] = {
    "0 = manual only. Pause also available from desktop Wallpaper Actions.": "0 = nur manuell. Pause auch über Hintergrundbild-Aktionen auf dem Desktop.",
    "%1 blocked wallpaper(s)": "%1 blockierte(s) Hintergrundbild(er)",
    "%1 cached wallpaper(s)": "%1 zwischengespeicherte(s) Hintergrundbild(er)",
    "6am–8pm": "6–20 Uhr",
    "8pm–6am": "20–6 Uhr",
    "Accept commands from plasmoid/CLI": "Befehle von Plasmoid/CLI akzeptieren",
    "Account blacklist:": "Konto-Sperrliste:",
    "Adaptive preload:": "Adaptives Vorladen:",
    "Advance all monitors in the same group together": "Alle Monitore in derselben Gruppe gemeinsam weiterschalten",
    "Advanced": "Erweitert",
    "All portrait": "Alle Hochformat",
    "All results are blocked. Clear the blocklist or try another search.": "Alle Ergebnisse sind blockiert. Leere die Sperrliste oder versuche eine andere Suche.",
    "All wide": "Alle Breitformat",
    "Anime:": "Anime:",
    "Any": "Beliebig",
    "API key:": "API-Schlüssel:",
    "API key is valid.": "API-Schlüssel ist gültig.",
    "API key (optional)": "API-Schlüssel (optional)",
    "API key required for favorites mode.": "API-Schlüssel für Favoritenmodus erforderlich.",
    "API key validation failed (%1).": "API-Schlüssel-Validierung fehlgeschlagen (%1).",
    "API order:": "API-Reihenfolge:",
    "API sorting:": "API-Sortierung:",
    "Apply accent color via plasma-apply-colors when available": "Akzentfarbe über plasma-apply-colors anwenden, wenn verfügbar",
    "Apply preset:": "Voreinstellung anwenden:",
    "Apply selected preset": "Ausgewählte Voreinstellung anwenden",
    "Apply Wallhaven as the wallpaper type to manage the blocklist.": "Wallhaven als Hintergrundtyp wählen, um die Sperrliste zu verwalten.",
    "Apply Wallhaven as the wallpaper type to see cache stats.": "Wallhaven als Hintergrundtyp wählen, um Cache-Statistiken zu sehen.",
    "Apply Wallhaven tag blacklist (Search + API key)": "Wallhaven-Tag-Sperrliste anwenden (Suche + API-Schlüssel)",
    "Ascending": "Aufsteigend",
    "Attribution:": "Namensnennung:",
    "Attribution corner:": "Ecke für Namensnennung:",
    "Auto-hide (sec):": "Autom. ausblenden (Sek.):",
    "Auto panel accent:": "Autom. Panel-Akzent:",
    "Avoid recent duplicates (saved across restarts)": "Kürzliche Duplikate vermeiden (über Neustarts gespeichert)",
    "Battery pause:": "Akku-Pause:",
    "Battery threshold (%):": "Akku-Schwellwert (%):",
    "Black": "Schwarz",
    "Blocked IDs:": "Blockierte IDs:",
    "Blocked wallpaper %1.": "Hintergrundbild %1 blockiert.",
    "Blocklist": "Sperrliste",
    "Blocklist cleared.": "Sperrliste geleert.",
    "Block the current wallpaper from desktop Wallpaper Actions. Blocked IDs are skipped during search.": "Aktuelles Hintergrundbild über Hintergrundbild-Aktionen blockieren. Blockierte IDs werden bei der Suche übersprungen.",
    "Block This Wallpaper": "Dieses Hintergrundbild blockieren",
    "Block wallpaper": "Hintergrundbild blockieren",
    "Blue": "Blau",
    "Blue Purple": "Blau Violett",
    "Bottom left": "Unten links",
    "Bottom right": "Unten rechts",
    "Bright Red": "Hellrot",
    "Bright Yellow": "Hellgelb",
    "Brown": "Braun",
    "Browse mode:": "Durchsuchmodus:",
    "Cached:": "Im Cache:",
    "Cache Manager": "Cache-Manager",
    "Cache recent wallpapers locally (faster revisits)": "Aktuelle Hintergrundbilder lokal zwischenspeichern (schnellerer Zugriff)",
    "Cache slots:": "Cache-Plätze:",
    "Cache status:": "Cache-Status:",
    "Categories": "Kategorien",
    "Category, purity, ratio, color, blacklist, and time-of-day filters apply to Search mode only. Collection and Favorites use the collection API as-is.": "Kategorie-, Reinheits-, Seitenverhältnis-, Farb-, Sperrlisten- und Tageszeitfilter gelten nur im Suchmodus. Sammlung und Favoriten nutzen die Sammlungs-API unverändert.",
    "Checking…": "Prüfe…",
    "Clear blocklist": "Sperrliste leeren",
    "Clear blocklist:": "Sperrliste leeren:",
    "Clear cache:": "Cache leeren:",
    "Clear disk cache": "Festplatten-Cache leeren",
    "Clear history:": "Verlauf leeren:",
    "Clear wallpaper history": "Hintergrundbild-Verlauf leeren",
    "Collection": "Sammlung",
    "Collection ID:": "Sammlungs-ID:",
    "Collection list:": "Sammlungsliste:",
    "Collections:": "Sammlungen:",
    "Collection user:": "Sammlungsbenutzer:",
    "Collection username and ID are required.": "Sammlungsbenutzername und ID sind erforderlich.",
    "Color:": "Farbe:",
    "Comma-separated tags boosted in search": "Kommagetrennte Tags, die in der Suche bevorzugt werden",
    "Comma-separated tags to exclude, e.g. nsfw, text": "Kommagetrennte auszuschließende Tags, z. B. nsfw, text",
    "Control bus:": "Steuerungsbus:",
    "Copied debug info.": "Debug-Info kopiert.",
    "Copied GitHub issue template.": "GitHub-Issue-Vorlage kopiert.",
    "Copied page URL.": "Seiten-URL kopiert.",
    "Copied tags.": "Tags kopiert.",
    "Copied wallpaper ID %1.": "Hintergrundbild-ID %1 kopiert.",
    "Copy debug info": "Debug-Info kopieren",
    "Copy GitHub issue template": "GitHub-Issue-Vorlage kopieren",
    "Copy Page URL": "Seiten-URL kopieren",
    "Copy preset share URL": "Voreinstellungs-URL kopieren",
    "Copy settings to clipboard": "Einstellungen in Zwischenablage kopieren",
    "Copy tags": "Tags kopieren",
    "Copy Tags": "Tags kopieren",
    "Copy Wallpaper ID": "Hintergrundbild-ID kopieren",
    "Could not download wallpaper images. Check your connection.": "Hintergrundbilder konnten nicht heruntergeladen werden. Verbindung prüfen.",
    "Could not download wallpaper to save.": "Hintergrundbild zum Speichern konnte nicht heruntergeladen werden.",
    "Could not import settings file.": "Einstellungsdatei konnte nicht importiert werden.",
    "Could not load community presets.": "Community-Voreinstellungen konnten nicht geladen werden.",
    "Could not load curated presets.": "Kuratierte Voreinstellungen konnten nicht geladen werden.",
    "Could not load the next wallpaper.": "Nächstes Hintergrundbild konnte nicht geladen werden.",
    "Could not load wallpaper.": "Hintergrundbild konnte nicht geladen werden.",
    "Could not parse collections response.": "Sammlungsantwort konnte nicht verarbeitet werden.",
    "Could not parse search response.": "Suchantwort konnte nicht verarbeitet werden.",
    "Could not read settings file.": "Einstellungsdatei konnte nicht gelesen werden.",
    "Could not save wallpaper.": "Hintergrundbild konnte nicht gespeichert werden.",
    "Crossfade": "Überblenden",
    "Crossfade (ms):": "Überblenden (ms):",
    "Current Wallpaper": "Aktuelles Hintergrundbild",
    "Cyan Blue": "Cyanblau",
    "Cycle through multiple collections on each advance": "Bei jedem Weiterschalten mehrere Sammlungen durchlaufen",
    "Dark Brown": "Dunkelbraun",
    "Dark Green": "Dunkelgrün",
    "Dark Orange": "Dunkelorange",
    "Dark Purple": "Dunkelviolett",
    "Dark Red": "Dunkelrot",
    "Date added": "Hinzugefügt am",
    "Day interval (min):": "Tag-Intervall (Min.):",
    "Day/night intervals override the base interval when set (6am–8pm = day).": "Tag-/Nacht-Intervalle überschreiben das Basisintervall (6–20 Uhr = Tag).",
    "Day search:": "Tagessuche:",
    "Debug info:": "Debug-Info:",
    "Debug log:": "Debug-Protokoll:",
    "default": "Standard",
    "Delete preset:": "Voreinstellung löschen:",
    "Delete selected preset": "Ausgewählte Voreinstellung löschen",
    "Descending": "Absteigend",
    "Desktop banner:": "Desktop-Banner:",
    "Diagnostics": "Diagnose",
    "Disk cache:": "Festplatten-Cache:",
    "Disk cache cleared.": "Festplatten-Cache geleert.",
    "Duplicates:": "Duplikate:",
    "Effects": "Effekte",
    "e.g. 1920x1080,2560x1440": "z. B. 1920x1080,2560x1440",
    "e.g. Anime night": "z. B. Anime Nacht",
    "Empty = screen height": "Leer = Bildschirmhöhe",
    "Empty = screen width": "Leer = Bildschirmbreite",
    "Enabled": "Aktiviert",
    "Enter an API key first.": "Zuerst einen API-Schlüssel eingeben.",
    "Evict": "Entfernen",
    "Exact resolutions:": "Exakte Auflösungen:",
    "Export:": "Exportieren:",
    "Export file:": "Exportdatei:",
    "Export Wallhaven Settings": "Wallhaven-Einstellungen exportieren",
    "External Control": "Externe Steuerung",
    "Fade through black": "Über Schwarz ausblenden",
    "Failed to load collections (%1).": "Sammlungen konnten nicht geladen werden (%1).",
    "Failed to load favorites (%1).": "Favoriten konnten nicht geladen werden (%1).",
    "Favorite on Wallhaven…": "Auf Wallhaven favorisieren…",
    "Favorites": "Favoriten",
    "Favorites refresh (min):": "Favoriten-Aktualisierung (Min.):",
    "Favorite tags:": "Bevorzugte Tags:",
    "File type:": "Dateityp:",
    "Filters": "Filter",
    "Filter settings…": "Einstellungen filtern…",
    "Finish": "Fertigstellen",
    "Font scale (%):": "Schriftgröße (%):",
    "Forest": "Waldgrün",
    "General:": "Allgemein:",
    "GitHub issue:": "GitHub-Issue:",
    "Gold": "Gold",
    "Gray": "Grau",
    "Green": "Grün",
    "Image failed to load. Trying another…": "Bild konnte nicht geladen werden. Versuche ein anderes…",
    "Image quality:": "Bildqualität:",
    "Images decode to screen size. Inactive crossfade layers are released, and settings preview writes are deferred.": "Bilder werden auf Bildschirmgröße dekodiert. Inaktive Überblendebenen werden freigegeben, Vorschau-Schreibvorgänge verzögert.",
    "Import:": "Importieren:",
    "Import community:": "Community importieren:",
    "Import community presets": "Community-Voreinstellungen importieren",
    "Import curated:": "Kuratiert importieren:",
    "Import curated presets": "Kuratierte Voreinstellungen importieren",
    "Imported %1 community preset(s).": "%1 Community-Voreinstellung(en) importiert.",
    "Imported %1 curated preset(s).": "%1 kuratierte Voreinstellung(en) importiert.",
    "Imported preset %1.": "Voreinstellung %1 importiert.",
    "Import preset from URL": "Voreinstellung von URL importieren",
    "Import settings from file…": "Einstellungen aus Datei importieren…",
    "Import URL:": "Import-URL:",
    "Import Wallhaven Settings": "Wallhaven-Einstellungen importieren",
    "Inactive pause:": "Inaktiv-Pause:",
    "Instant": "Sofort",
    "Interval jitter (%):": "Intervall-Streuung (%):",
    "Interval (min):": "Intervall (Min.):",
    "Invalid preset URL.": "Ungültige Voreinstellungs-URL.",
    "JPEG image (*.jpg *.jpeg)": "JPEG-Bild (*.jpg *.jpeg)",
    "JSON files (*.json)": "JSON-Dateien (*.json)",
    "Ken Burns:": "Ken Burns:",
    "Ken Burns speed:": "Ken-Burns-Geschwindigkeit:",
    "KWallet:": "KWallet:",
    "Large (full wallpaper)": "Groß (volles Hintergrundbild)",
    "Light Gray": "Hellgrau",
    "Load API key from KWallet on startup": "API-Schlüssel beim Start aus KWallet laden",
    "Load collections": "Sammlungen laden",
    "Loading…": "Lade…",
    "Loading next cached wallpaper…": "Lade nächstes zwischengespeichertes Hintergrundbild…",
    "Loading next wallpaper…": "Lade nächstes Hintergrundbild…",
    "Loading wallpapers similar to %1…": "Lade ähnliche Hintergrundbilder zu %1…",
    "Local sorting:": "Lokale Sortierung:",
    "Lock screen:": "Sperrbildschirm:",
    "Manual": "Manuell",
    "Max retry attempts:": "Max. Wiederholungsversuche:",
    "Metered network:": "Getaktetes Netzwerk:",
    "Min height:": "Mindesthöhe:",
    "Min width:": "Mindestbreite:",
    "Mon–Fri": "Mo–Fr",
    "More actions": "Weitere Aktionen",
    "Must match wallpaper Advanced → Sync group": "Muss mit Hintergrund Erweitert → Sync-Gruppe übereinstimmen",
    "Network error during search test.": "Netzwerkfehler beim Suchtest.",
    "Network error while loading collections.": "Netzwerkfehler beim Laden der Sammlungen.",
    "Network error while validating API key.": "Netzwerkfehler bei der API-Schlüssel-Validierung.",
    "Network restored. Resuming…": "Netzwerk wiederhergestellt. Setze fort…",
    "Network & Retries": "Netzwerk & Wiederholungen",
    "Never use the network; cycle cached wallpapers only": "Netzwerk nie nutzen; nur zwischengespeicherte Hintergrundbilder durchlaufen",
    "Next wallpaper": "Nächstes Hintergrundbild",
    "Next Wallpaper": "Nächstes Hintergrundbild",
    "Night interval (min):": "Nacht-Intervall (Min.):",
    "Night search:": "Nachtsuche:",
    "No cached wallpapers available.": "Keine zwischengespeicherten Hintergrundbilder verfügbar.",
    "No collections found for this API key.": "Keine Sammlungen für diesen API-Schlüssel gefunden.",
    "No favorites collection found.": "Keine Favoriten-Sammlung gefunden.",
    "No more wallpapers match your current filters.": "Keine weiteren Hintergrundbilder entsprechen den aktuellen Filtern.",
    "No previous wallpaper in history.": "Kein vorheriges Hintergrundbild im Verlauf.",
    "Notifications": "Benachrichtigungen",
    "No wallpaper available to save.": "Kein Hintergrundbild zum Speichern verfügbar.",
    "No wallpaper loaded yet. Apply Wallhaven as the wallpaper type and wait for the first image.": "Noch kein Hintergrundbild geladen. Wallhaven als Hintergrundtyp wählen und auf das erste Bild warten.",
    "No wallpapers match your current filters.": "Keine Hintergrundbilder entsprechen den aktuellen Filtern.",
    "NSFW:": "NSFW:",
    "Offline fallback:": "Offline-Fallback:",
    "Offline mode — showing cached wallpaper.": "Offline-Modus — zeige zwischengespeichertes Hintergrundbild.",
    "Offline only:": "Nur offline:",
    "Olive": "Oliv",
    "On errors:": "Bei Fehlern:",
    "On refresh:": "Bei Aktualisierung:",
    "Opened on Wallhaven — use the heart button to favorite (no public write API).": "Auf Wallhaven geöffnet — Herz-Schaltfläche zum Favorisieren (keine öffentliche Schreib-API).",
    "Open in browser": "Im Browser öffnen",
    "Open in Browser": "Im Browser öffnen",
    "Optional: add your Wallhaven API key for NSFW and favorites.": "Optional: Wallhaven-API-Schlüssel für NSFW und Favoriten hinzufügen.",
    "Optional path for Variety integration": "Optionaler Pfad für Variety-Integration",
    "Optional; required for NSFW and favorites": "Optional; erforderlich für NSFW und Favoriten",
    "Orange": "Orange",
    "Original (full wallpaper)": "Original (volles Hintergrundbild)",
    "Other": "Sonstige",
    "Panel tint hint:": "Panel-Farbhinweis:",
    "Parallax:": "Parallax:",
    "Parallax strength:": "Parallax-Stärke:",
    "Pause:": "Pause:",
    "Pause automatic slideshow": "Automatische Diashow pausieren",
    "Paused": "Pausiert",
    "Pause slideshow": "Diashow pausieren",
    "Pause Slideshow": "Diashow pausieren",
    "Pause slideshow on low battery": "Diashow bei niedrigem Akkustand pausieren",
    "Pause when Plasma session is inactive": "Pausieren, wenn Plasma-Sitzung inaktiv ist",
    "People:": "Menschen:",
    "Performance": "Leistung",
    "Per-monitor profiles: set a different sync group and search on each screen, or the same group to advance together.": "Pro-Monitor-Profile: unterschiedliche Sync-Gruppe und Suche pro Bildschirm oder dieselbe Gruppe zum gemeinsamen Weiterschalten.",
    "Pick collection:": "Sammlung wählen:",
    "Pin": "Anheften",
    "Pink": "Rosa",
    "Pink Red": "Rosa Rot",
    "Playback": "Wiedergabe",
    "PNG image (*.png)": "PNG-Bild (*.png)",
    "Preload count:": "Vorladeanzahl:",
    "Preset name:": "Voreinstellungsname:",
    "Preset share URL copied.": "Voreinstellungs-URL kopiert.",
    "Preset URL:": "Voreinstellungs-URL:",
    "Previous wallpaper": "Vorheriges Hintergrundbild",
    "Previous Wallpaper": "Vorheriges Hintergrundbild",
    "Purity": "Reinheit",
    "Purple": "Violett",
    "Random": "Zufällig",
    "Rate limited by Wallhaven. Retry %1/%2 in %3s…": "Von Wallhaven ratenbegrenzt. Wiederholung %1/%2 in %3s…",
    "Ratio:": "Seitenverhältnis:",
    "Recent:": "Zuletzt:",
    "Red": "Rot",
    "Reduce preloads when offline or metered": "Vorladen bei Offline oder getaktetem Netz reduzieren",
    "Refresh cached wallpapers": "Zwischengespeicherte Hintergrundbilder aktualisieren",
    "Refresh cache list:": "Cache-Liste aktualisieren:",
    "Refresh history:": "Verlauf aktualisieren:",
    "Refresh history gallery": "Verlaufs-Galerie aktualisieren",
    "Relevance": "Relevanz",
    "Reloading wallpapers…": "Lade Hintergrundbilder neu…",
    "Reload wallpaper": "Hintergrundbild neu laden",
    "Reload Wallpaper": "Hintergrundbild neu laden",
    "Request failed (%1). Retry %2/%3 in %4s…": "Anfrage fehlgeschlagen (%1). Wiederholung %2/%3 in %4s…",
    "Request timed out. Retry %1/%2 in %3s…": "Zeitüberschreitung. Wiederholung %1/%2 in %3s…",
    "Request timeout (sec):": "Anfrage-Timeout (Sek.):",
    "Resolution & Ratio": "Auflösung & Seitenverhältnis",
    "Resume slideshow": "Diashow fortsetzen",
    "Resume Slideshow": "Diashow fortsetzen",
    "Retry delay (sec):": "Wiederholungsverzögerung (Sek.):",
    "Rotate collections:": "Sammlungen rotieren:",
    "Sat–Sun": "Sa–So",
    "Save current search": "Aktuelle Suche speichern",
    "Saved presets:": "Gespeicherte Voreinstellungen:",
    "Save preset:": "Voreinstellung speichern:",
    "Save settings to file…": "Einstellungen in Datei speichern…",
    "Save Wallpaper": "Hintergrundbild speichern",
    "Save Wallpaper…": "Hintergrundbild speichern…",
    "Saving wallpaper…": "Speichere Hintergrundbild…",
    "Search": "Suche",
    "Search Presets": "Voreinstellungen suchen",
    "Search string:": "Suchbegriff:",
    "Search tags, e.g. nature landscape": "Such-Tags, z. B. nature landscape",
    "Search test: %1 result(s).": "Suchtest: %1 Ergebnis(se).",
    "Search test failed (%1).": "Suchtest fehlgeschlagen (%1).",
    "Sent preset import request.": "Voreinstellungs-Import angefordert.",
    "Set color filter from current wallpaper palette": "Farbfilter aus aktueller Hintergrundbild-Palette setzen",
    "Settings Backup": "Einstellungs-Backup",
    "Settings copied to clipboard as JSON.": "Einstellungen als JSON in Zwischenablage kopiert.",
    "Settings exported.": "Einstellungen exportiert.",
    "Settings exported to file.": "Einstellungen in Datei exportiert.",
    "Settings imported.": "Einstellungen importiert.",
    "Setup wizard:": "Einrichtungsassistent:",
    "SFW:": "SFW:",
    "Share preset:": "Voreinstellung teilen:",
    "Show cached wallpapers when the network fails": "Zwischengespeicherte Hintergrundbilder bei Netzwerkfehler anzeigen",
    "Showing cached wallpaper (offline).": "Zeige zwischengespeichertes Hintergrundbild (offline).",
    "Showing wallpaper #%1 from history.": "Zeige Hintergrundbild #%1 aus dem Verlauf.",
    "Show overlay on desktop": "Overlay auf Desktop anzeigen",
    "Show setup wizard again": "Einrichtungsassistent erneut anzeigen",
    "Show status messages on the wallpaper": "Statusmeldungen auf dem Hintergrundbild anzeigen",
    "Similar Wallpapers": "Ähnliche Hintergrundbilder",
    "Sketchy:": "Anzüglich:",
    "Skip": "Überspringen",
    "Slate": "Schiefergrau",
    "Slide": "Schieben",
    "Slideshow": "Diashow",
    "Slideshow interval (min):": "Diashow-Intervall (Min.):",
    "Slideshow paused": "Diashow pausiert",
    "Slideshow paused.": "Diashow pausiert.",
    "Slideshow paused by power/activity rules.": "Diashow durch Energie-/Aktivitätsregeln pausiert.",
    "Slideshow resumed.": "Diashow fortgesetzt.",
    "Slideshow rules": "Diashow-Regeln",
    "Slow pan/zoom": "Langsames Schwenken/Zoomen",
    "Small (thumbnail, low bandwidth)": "Klein (Vorschau, geringe Bandbreite)",
    "Smart color search:": "Intelligente Farbsuche:",
    "Source": "Quelle",
    "Subtle per-screen wallpaper offset": "Dezenter Hintergrundbild-Versatz pro Bildschirm",
    "Symlink cached wallpaper as wallhaven-current.jpg": "Zwischengespeichertes Hintergrundbild als wallhaven-current.jpg verlinken",
    "Sync advance:": "Sync-Weiterschaltung:",
    "Sync group:": "Sync-Gruppe:",
    "Sync lock screen wallpaper when cached": "Sperrbildschirm-Hintergrund synchronisieren, wenn im Cache",
    "System color scheme": "System-Farbschema",
    "System notification for errors and warnings": "Systembenachrichtigung bei Fehlern und Warnungen",
    "System notification when wallpaper changes": "Systembenachrichtigung bei Hintergrundbildwechsel",
    "Tag blocklist:": "Tag-Sperrliste:",
    "Tags, keywords, e.g. nature anime": "Tags, Stichwörter, z. B. nature anime",
    "Tan": "Beige",
    "Teal": "Blaugrün",
    "Test API key": "API-Schlüssel testen",
    "Testing…": "Teste…",
    "Test search": "Suche testen",
    "Test search:": "Suche testen:",
    "Timed out while loading collections.": "Zeitüberschreitung beim Laden der Sammlungen.",
    "Time of day:": "Tageszeit:",
    "Time of Day": "Tageszeit",
    "Time-of-day searches apply in Search mode only (6am–8pm day, otherwise night).": "Tageszeitsuchen gelten nur im Suchmodus (6–20 Uhr Tag, sonst Nacht).",
    "Timeout is per request. Retries use the delay with exponential backoff, up to the max attempts.": "Timeout pro Anfrage. Wiederholungen mit Verzögerung und exponentiellem Backoff bis max. Versuche.",
    "Top left": "Oben links",
    "Toplist": "Topliste",
    "Toplist range:": "Toplisten-Zeitraum:",
    "Top right": "Oben rechts",
    "Transition:": "Übergang:",
    "Unpin": "Loslösen",
    "Use cache only on cellular connections": "Cache nur bei Mobilfunkverbindungen nutzen",
    "Username for collection/favorites override": "Benutzername für Sammlungs-/Favoriten-Override",
    "username/id per line (optional # label)": "Benutzername/ID pro Zeile (optional # Bezeichnung)",
    "Use separate day/night searches": "Getrennte Tag-/Nachtsuchen verwenden",
    "Use separate weekday/weekend searches": "Getrennte Wochentags-/Wochenendsuchen verwenden",
    "Use today's Wallhaven toplist (overrides sorting)": "Heutige Wallhaven-Topliste verwenden (überschreibt Sortierung)",
    "Use tools/wallhaven-ctl.sh, D-Bus (tools/wallhaven-dbus.py), or the Wallhaven Control plasmoid.": "tools/wallhaven-ctl.sh, D-Bus (tools/wallhaven-dbus.py) oder das Wallhaven-Control-Plasmoid verwenden.",
    "Validate key:": "Schlüssel validieren:",
    "Variety folder:": "Variety-Ordner:",
    "Variety metadata:": "Variety-Metadaten:",
    "Variety symlink:": "Variety-Symlink:",
    "Variety bridge:": "Variety-Brücke:",
    "Apply Variety search to Wallhaven": "Variety-Suche auf Wallhaven anwenden",
    "No Variety config found.": "Keine Variety-Konfiguration gefunden.",
    "No image_fetch_search in Variety config.": "Kein image_fetch_search in Variety-Konfiguration.",
    "Applied Variety search: %1": "Variety-Suche angewendet: %1",
    "Views": "Aufrufe",
    "Wallhaven": "Wallhaven",
    "wallhaven://preset/…": "wallhaven://preset/…",
    "Wallhaven request failed after %1 attempts.": "Wallhaven-Anfrage nach %1 Versuchen fehlgeschlagen.",
    "Wallpaper #%1": "Hintergrundbild #%1",
    "Wallpaper Actions: Reload / Next / Similar / Pause / Copy / Block / Save.": "Hintergrundbild-Aktionen: Neu laden / Weiter / Ähnlich / Pause / Kopieren / Blockieren / Speichern.",
    "Wallpaper History": "Hintergrundbild-Verlauf",
    "Wallpaper history cleared.": "Hintergrundbild-Verlauf geleert.",
    "Wallpaper of the day:": "Hintergrundbild des Tages:",
    "Wallpaper saved.": "Hintergrundbild gespeichert.",
    "Weekday Schedule": "Wochentagsplan",
    "Weekday search:": "Wochentagssuche:",
    "Weekday/weekend searches apply in Search mode when time-of-day is disabled.": "Wochentags-/Wochenendsuchen gelten im Suchmodus, wenn Tageszeit deaktiviert ist.",
    "Weekend search:": "Wochenendsuche:",
    "Week schedule:": "Wochenplan:",
    "Welcome to Wallhaven for Plasma": "Willkommen bei Wallhaven für Plasma",
    "White": "Weiß",
    "Write current wallpaper JSON for external tools": "Aktuelles Hintergrundbild-JSON für externe Tools schreiben",
    "Write debug events to cache log file": "Debug-Ereignisse in Cache-Protokolldatei schreiben",
    "Write dominant color JSON for external theming tools": "Dominante-Farbe-JSON für externe Design-Tools schreiben",
    "Yellow": "Gelb",
    "Yellow Green": "Gelbgrün",
    "Zoom": "Zoom",
}


def parse_pot(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8")
    msgids: list[str] = []
    for block in re.split(r"\n\n+", text):
        m = re.search(r'^msgid "(.*)"$', block, re.M)
        if not m:
            continue
        msgid = m.group(1).replace('\\"', '"').replace("\\n", "\n")
        if msgid:
            msgids.append(msgid)
    return msgids


def escape_po(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def write_po(path: Path, lang: str, version: str, entries: list[tuple[str, str]]) -> None:
    lines = [
        'msgid ""',
        'msgstr ""',
        f'"Project-Id-Version: org.robertsm.wallhaven {version}\\n"',
        f'"Language: {lang}\\n"',
        '"MIME-Version: 1.0\\n"',
        '"Content-Type: text/plain; charset=UTF-8\\n"',
        "",
    ]
    for msgid, msgstr in entries:
        lines.append(f'msgid "{escape_po(msgid)}"')
        lines.append(f'msgstr "{escape_po(msgstr)}"')
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    version = "1.7.0"
    meta = ROOT / "metadata.json"
    if meta.exists():
        import re as _re
        m = _re.search(r'"Version"\s*:\s*"([^"]+)"', meta.read_text(encoding="utf-8"))
        if m:
            version = m.group(1)
    if not POT.exists():
        print(f"Missing {POT}; run scripts/extract-messages.sh first", file=sys.stderr)
        return 1

    msgids = parse_pot(POT)
    missing: list[str] = []
    de_entries: list[tuple[str, str]] = []
    en_entries: list[tuple[str, str]] = []

    for msgid in msgids:
        if msgid not in DE:
            missing.append(msgid)
            de_entries.append((msgid, msgid))  # fallback
        else:
            de_entries.append((msgid, DE[msgid]))
        en_entries.append((msgid, msgid))

    write_po(DE_PO, "de", version, de_entries)
    write_po(ROOT / "po" / "en.po", "en", version, en_entries)

    if missing:
        print(f"Warning: {len(missing)} strings without German translation (using English fallback):")
        for item in missing[:10]:
            print(f"  - {item}")
        if len(missing) > 10:
            print(f"  ... and {len(missing) - 10} more")
    else:
        print(f"Wrote complete German translations for {len(de_entries)} strings")

    print(f"Updated {DE_PO} and po/en.po")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
